### ISSUE TITLE
Add-on does not work on Windows 10 home

### ISSUE THREAD

**Issue by Mojay1664** [NumesSanguis/Blender-ZMQ-add-on#1]
Hi Numes - any chance of getting this working on W10 home edition?

**Comment by NumesSanguis** [comment]
It's not working on any platform yet, haha. That's why there is the note: "**WARNING: CODE STILL IN PROGRESS and INSTRUCTIONS NOT COMPLETE**". Also there is still something under "TODO".

If you really can't wait, you have to find out by yourself how to install `pyzmq` in Blender or manage to link Blender to a Python environment with `pyzmq`.

If it still doesn't work after I added the finishing touches to this add-on (hopefully this week, maybe next week), then please post again and include what error you get / which step is not working :)

**Comment by NumesSanguis** [comment]
Just gave the final update. Everything should work now ^-^ Please try again.
